<a href="https://colab.research.google.com/github/77mostafaayman77/5G-Resource-Allocation-QoS-Prediction/blob/main/5G_Resource_Allocation_%26_QoS_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
from google.colab import userdata

os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

# Download Data from Kaggle
!kaggle datasets download -d omarsobhy14/5g-quality-of-service

# Extract csv file
!unzip 5g-quality-of-service.zip

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.1), please consider upgrading to the latest version (2.0.2)
Dataset URL: https://www.kaggle.com/datasets/omarsobhy14/5g-quality-of-service
License(s): other
5g-quality-of-service.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  5g-quality-of-service.zip
replace Quality of Service 5G.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: Quality of Service 5G.csv

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Quality of Service 5G.csv")

In [ ]:
df.head()

,Timestamp,User_ID,Application_Type,Signal_Strength,Latency,Required_Bandwidth,Allocated_Bandwidth,Resource_Allocation
0,9/3/2023 10:00,User_1,Video_Call,-75 dBm,30 ms,10 Mbps,15 Mbps,70%
1,9/3/2023 10:00,User_2,Voice_Call,-80 dBm,20 ms,100 Kbps,120 Kbps,80%
2,9/3/2023 10:00,User_3,Streaming,-85 dBm,40 ms,5 Mbps,6 Mbps,75%
3,9/3/2023 10:00,User_4,Emergency_Service,-70 dBm,10 ms,1 Mbps,1.5 Mbps,90%
4,9/3/2023 10:00,User_5,Online_Gaming,-78 dBm,25 ms,2 Mbps,3 Mbps,85%

In [ ]:
df.shape

(400, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            400 non-null    object
 1   User_ID              400 non-null    object
 2   Application_Type     400 non-null    object
 3   Signal_Strength      400 non-null    object
 4   Latency              400 non-null    object
 5   Required_Bandwidth   400 non-null    object
 6   Allocated_Bandwidth  400 non-null    object
 7   Resource_Allocation  400 non-null    object
dtypes: object(8)
memory usage: 25.1+ KB

In [ ]:
df.describe()

,Timestamp,User_ID,Application_Type,Signal_Strength,Latency,Required_Bandwidth,Allocated_Bandwidth,Resource_Allocation
count,400,400,400,400,400,400,400,400
unique,7,400,11,84,87,188,194,9
top,9/3/2023 10:01,User_384,Video_Call,-85 dBm,5 ms,0.1 Mbps,0.1 Mbps,70%
freq,60,1,58,9,35,16,16,148

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean = df_clean.drop(['Timestamp','User_ID'], axis='columns')
df_clean.head()

,Application_Type,Signal_Strength,Latency,Required_Bandwidth,Allocated_Bandwidth,Resource_Allocation
0,Video_Call,-75 dBm,30 ms,10 Mbps,15 Mbps,70%
1,Voice_Call,-80 dBm,20 ms,100 Kbps,120 Kbps,80%
2,Streaming,-85 dBm,40 ms,5 Mbps,6 Mbps,75%
3,Emergency_Service,-70 dBm,10 ms,1 Mbps,1.5 Mbps,90%
4,Online_Gaming,-78 dBm,25 ms,2 Mbps,3 Mbps,85%

In [ ]:
for column in df_clean.columns:
  print(f"{column}: {df_clean[column].unique()} \n")

Application_Type: ['Video_Call' 'Voice_Call' 'Streaming' 'Emergency_Service' 'Online_Gaming'
 'Background_Download' 'Web_Browsing' 'IoT_Temperature' 'Video_Streaming'
 'File_Download' 'VoIP_Call']

Signal_Strength: ['-75 dBm' '-80 dBm' '-85 dBm' '-70 dBm' '-78 dBm' '-90 dBm' '-88 dBm'
 '-95 dBm' '-82 dBm' '-76 dBm' '-79 dBm' '-87 dBm' '-81 dBm' '-74 dBm'
 '-84 dBm' '-69 dBm' '-91 dBm' '-96 dBm' '-83 dBm' '-77 dBm' '-86 dBm'
 '-73 dBm' '-68 dBm' '-92 dBm' '-97 dBm' '-72 dBm' '-67 dBm' '-93 dBm'
 '-98 dBm' '-71 dBm' '-66 dBm' '-94 dBm' '-99 dBm' '-89 dBm' '-65 dBm'
 '-100 dBm' '-64 dBm' '-101 dBm' '-63 dBm' '-102 dBm' '-62 dBm' '-103 dBm'
 '-61 dBm' '-104 dBm' '-60 dBm' '-59 dBm' '-58 dBm' '-57 dBm' '-56 dBm'
 '-55 dBm' '-54 dBm' '-53 dBm' '-52 dBm' '-51 dBm' '-105 dBm' '-50 dBm'
 '-106 dBm' '-107 dBm' '-49 dBm' '-108 dBm' '-109 dBm' '-48 dBm'
 '-110 dBm' '-111 dBm' '-47 dBm' '-112 dBm' '-113 dBm' '-46 dBm'
 '-114 dBm' '-115 dBm' '-45 dBm' '-116 dBm' '-44 dBm' '-117 dBm'
 '-118 dBm' '-43 dBm' '-119 dBm' '-42 dBm' '-120 dBm' '-121 dBm' '-41 dBm'
 '-122 dBm' '-40 dBm' '-123 dBm']

Latency: ['30 ms' '20 ms' '40 ms' '10 ms' '25 ms' '50 ms' '100 ms' '35 ms' '45 ms'
 '32 ms' '24 ms' '28 ms' '22 ms' '29 ms' '38 ms' '9 ms' '48 ms' '105 ms'
 '34 ms' '31 ms' '23 ms' '21 ms' '37 ms' '8 ms' '47 ms' '110 ms' '33 ms'
 '27 ms' '36 ms' '7 ms' '46 ms' '26 ms' '104 ms' '103 ms' '102 ms' '19 ms'
 '6 ms' '44 ms' '101 ms' '18 ms' '43 ms' '17 ms' '42 ms' '99 ms' '5 ms'
 '49 ms' '51 ms' '52 ms' '53 ms' '54 ms' '55 ms' '56 ms' '39 ms' '16 ms'
 '57 ms' '15 ms' '58 ms' '41 ms' '14 ms' '59 ms' '13 ms' '60 ms' '12 ms'
 '61 ms' '11 ms' '62 ms' '63 ms' '64 ms' '65 ms' '66 ms' '67 ms' '68 ms'
 '4 ms' '69 ms' '3 ms' '70 ms' '2 ms' '71 ms' '1 ms' '72 ms' '0 ms'
 '73 ms' '74 ms' '75 ms' '76 ms' '77 ms' '78 ms']

Required_Bandwidth: ['10 Mbps' '100 Kbps' '5 Mbps' '1 Mbps' '2 Mbps' '500 Kbps' '10 Kbps'
 '3 Mbps' '12 Mbps' '2.5 Mbps' '1.2 Mbps' '150 Kbps' '4.5 Mbps' '600 Kbps'
 '8 Kbps' '3.2 Mbps' '11 Mbps' '2.2 Mbps' '1.4 Mbps' '160 Kbps'
 '10.5 Mbps' '4.2 Mbps' '1.1 Mbps' '620 Kbps' '7 Kbps' '3.4 Mbps'
 '10.2 Mbps' '2.3 Mbps' '1.3 Mbps' '170 Kbps' '10.8 Mbps' '4.0 Mbps'
 '1.0 Mbps' '630 Kbps' '6 Kbps' '3.5 Mbps' '2.4 Mbps' '165 Kbps'
 '3.8 Mbps' '640 Kbps' '5 Kbps' '3.6 Mbps' '2.6 Mbps' '10.7 Mbps'
 '4.1 Mbps' '650 Kbps' '4 Kbps' '3.7 Mbps' '10.3 Mbps' '2.7 Mbps'
 '155 Kbps' '10.9 Mbps' '4.3 Mbps' '660 Kbps' '3 Kbps' '2.8 Mbps'
 '0.9 Mbps' '11.0 Mbps' '4.4 Mbps' '670 Kbps' '2 Kbps' '3.9 Mbps'
 '2.9 Mbps' '0.8 Mbps' '145 Kbps' '11.2 Mbps' '680 Kbps' '1 Kbps'
 '3.0 Mbps' '0.7 Mbps' '140 Kbps' '11.4 Mbps' '4.6 Mbps' '690 Kbps'
 '3.1 Mbps' '1.5 Mbps' '130 Kbps' '5.0 Mbps' '0.6 Mbps' '11.1 Mbps'
 '610 Kbps' '125 Kbps' '3.3 Mbps' '11.3 Mbps' '120 Kbps' '11.5 Mbps'
 '0.5 Mbps' '115 Kbps' '11.6 Mbps' '110 Kbps' '11.7 Mbps' '105 Kbps'
 '11.8 Mbps' '11.9 Mbps' '0.4 Mbps' '95 Kbps' '12.0 Mbps' '590 Kbps'
 '90 Kbps' '12.1 Mbps' '580 Kbps' '85 Kbps' '12.2 Mbps' '570 Kbps'
 '80 Kbps' '12.3 Mbps' '560 Kbps' '75 Kbps' '12.4 Mbps' '0.3 Mbps'
 '550 Kbps' '70 Kbps' '12.5 Mbps' '540 Kbps' '65 Kbps' '12.6 Mbps'
 '530 Kbps' '60 Kbps' '12.7 Mbps' '0.2 Mbps' '520 Kbps' '55 Kbps'
 '12.8 Mbps' '510 Kbps' '50 Kbps' '4.7 Mbps' '12.9 Mbps' '45 Kbps'
 '4.8 Mbps' '13.0 Mbps' '0.1 Mbps' '490 Kbps' '40 Kbps' '4.9 Mbps'
 '13.1 Mbps' '480 Kbps' '35 Kbps' '13.2 Mbps' '470 Kbps' '30 Kbps'
 '5.1 Mbps' '13.3 Mbps' '460 Kbps' '25 Kbps' '5.2 Mbps' '13.4 Mbps'
 '2.1 Mbps' '450 Kbps' '20 Kbps' '5.3 Mbps' '13.5 Mbps' '2.0 Mbps'
 '440 Kbps' '15 Kbps' '5.4 Mbps' '13.6 Mbps' '1.9 Mbps' '430 Kbps'
 '5.5 Mbps' '13.7 Mbps' '1.8 Mbps' '420 Kbps' '5.6 Mbps' '13.8 Mbps'
 '1.7 Mbps' '410 Kbps' '0 Kbps' '5.7 Mbps' '13.9 Mbps' '1.6 Mbps'
 '400 Kbps' '5.8 Mbps' '14.0 Mbps' '390 Kbps' '5.9 Mbps' '14.1 Mbps'
 '380 Kbps' '6.0 Mbps' '14.2 Mbps' '370 Kbps' '6.1 Mbps' '14.3 Mbps'
 '360 Kbps' '6.2 Mbps' '14.4 Mbps' '350 Kbps' '6.3 Mbps' '14.5 Mbps']

Allocated_Bandwidth: ['15 Mbps' '120 Kbps' '6 Mbps' '1.5 Mbps' '3 Mbps' '550 Kbps' '1 Mbps'
 '15 Kbps' '3.5 Mbps' '2 Mbps' '14 Mbps' '2.8 Mbps' '1.2 Mbps' '170 Kbps'
 '12 Mbps' '5 Mbps' '1.3 Mbps' '600 Kbps' '9 Kbps' '13 Mbps' '2.5 Mbps'
 '1.4 Mbps' '180 Kbps' '12.5 Mbps' '4.8 Mbps' '620 Kbps' '8 Kbps'
 '3.7 Mbps' '12.2 Mbps' '2.6 Mbps' '190 Kbps' '12.8 Mbps' '4.6 Mbps'
 '1.1 Mbps' '630 Kbps' '7 Kbps' '3.8 Mbps' '12.3 Mbps' '2.7 Mbps'
 '185 Kbps' '12.6 Mbps' '4.4 Mbps' '640 Kbps' '6 Kbps' '3.9 Mbps'
 '2.9 Mbps' '4.7 Mbps' '650 Kbps' '5 Kbps' '4.0 Mbps' '12.1 Mbps'
 '3.0 Mbps' '1.0 Mbps' '12.4 Mbps' '4.9 Mbps' '660 Kbps' '4 Kbps'
 '4.1 Mbps' '3.1 Mbps' '0.9 Mbps' '175 Kbps' '5.0 Mbps' '670 Kbps'
 '3 Kbps' '4.2 Mbps' '12.0 Mbps' '3.2 Mbps' '0.8 Mbps' '5.1 Mbps'
 '680 Kbps' '2 Kbps' '4.3 Mbps' '3.3 Mbps' '0.7 Mbps' '165 Kbps'
 '12.7 Mbps' '5.2 Mbps' '690 Kbps' '3.4 Mbps' '155 Kbps' '5.7 Mbps'
 '0.6 Mbps' '4.5 Mbps' '610 Kbps' '150 Kbps' '3.6 Mbps' '145 Kbps'
 '0.5 Mbps' '140 Kbps' '12.9 Mbps' '135 Kbps' '13.0 Mbps' '130 Kbps'
 '13.1 Mbps' '125 Kbps' '13.2 Mbps' '0.4 Mbps' '13.3 Mbps' '590 Kbps'
 '115 Kbps' '13.4 Mbps' '580 Kbps' '110 Kbps' '13.5 Mbps' '570 Kbps'
 '105 Kbps' '13.6 Mbps' '560 Kbps' '100 Kbps' '13.7 Mbps' '0.3 Mbps'
 '95 Kbps' '13.8 Mbps' '540 Kbps' '90 Kbps' '13.9 Mbps' '530 Kbps'
 '85 Kbps' '14.0 Mbps' '0.2 Mbps' '520 Kbps' '80 Kbps' '14.1 Mbps'
 '510 Kbps' '75 Kbps' '14.2 Mbps' '500 Kbps' '70 Kbps' '14.3 Mbps'
 '0.1 Mbps' '490 Kbps' '65 Kbps' '14.4 Mbps' '480 Kbps' '60 Kbps'
 '5.3 Mbps' '14.5 Mbps' '470 Kbps' '55 Kbps' '5.4 Mbps' '14.6 Mbps'
 '460 Kbps' '50 Kbps' '5.5 Mbps' '14.7 Mbps' '450 Kbps' '45 Kbps'
 '5.6 Mbps' '14.8 Mbps' '2.4 Mbps' '440 Kbps' '40 Kbps' '14.9 Mbps'
 '2.3 Mbps' '430 Kbps' '35 Kbps' '5.8 Mbps' '15.0 Mbps' '2.2 Mbps'
 '420 Kbps' '30 Kbps' '5.9 Mbps' '15.1 Mbps' '2.1 Mbps' '410 Kbps'
 '25 Kbps' '6.0 Mbps' '15.2 Mbps' '2.0 Mbps' '400 Kbps' '20 Kbps'
 '6.1 Mbps' '15.3 Mbps' '1.9 Mbps' '390 Kbps' '6.2 Mbps' '15.4 Mbps'
 '1.8 Mbps' '380 Kbps' '10 Kbps' '6.3 Mbps' '15.5 Mbps' '1.7 Mbps'
 '370 Kbps' '6.4 Mbps' '15.6 Mbps' '1.6 Mbps' '360 Kbps' '0 Kbps'
 '6.5 Mbps' '15.7 Mbps' '350 Kbps' '6.6 Mbps' '15.8 Mbps']

Resource_Allocation: ['70%' '80%' '75%' '90%' '85%' '60%' '50%' '65%' '55%']

In [ ]:
df_clean['Resource_Allocation'] = df_clean['Resource_Allocation'].str.replace('%','').astype('int') / 100
df_clean.head()

,Application_Type,Signal_Strength,Latency,Required_Bandwidth,Allocated_Bandwidth,Resource_Allocation
0,Video_Call,-75 dBm,30 ms,10 Mbps,15 Mbps,0.70
1,Voice_Call,-80 dBm,20 ms,100 Kbps,120 Kbps,0.80
2,Streaming,-85 dBm,40 ms,5 Mbps,6 Mbps,0.75
3,Emergency_Service,-70 dBm,10 ms,1 Mbps,1.5 Mbps,0.90
4,Online_Gaming,-78 dBm,25 ms,2 Mbps,3 Mbps,0.85

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Application_Type     400 non-null    object
 1   Signal_Strength      400 non-null    object
 2   Latency              400 non-null    object
 3   Required_Bandwidth   400 non-null    object
 4   Allocated_Bandwidth  400 non-null    object
 5   Resource_Allocation  400 non-null    float64
dtypes: float64(1), object(5)
memory usage: 18.9+ KB

In [ ]:
df_clean['Latency'] = df_clean['Latency'].str.replace('ms','').astype('float') / 1000
df_clean.head()

,Application_Type,Signal_Strength,Latency,Required_Bandwidth,Allocated_Bandwidth,Resource_Allocation
0,Video_Call,-75 dBm,0.030,10 Mbps,15 Mbps,0.70
1,Voice_Call,-80 dBm,0.020,100 Kbps,120 Kbps,0.80
2,Streaming,-85 dBm,0.040,5 Mbps,6 Mbps,0.75
3,Emergency_Service,-70 dBm,0.010,1 Mbps,1.5 Mbps,0.90
4,Online_Gaming,-78 dBm,0.025,2 Mbps,3 Mbps,0.85

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Application_Type     400 non-null    object
 1   Signal_Strength      400 non-null    object
 2   Latency              400 non-null    float64
 3   Required_Bandwidth   400 non-null    object
 4   Allocated_Bandwidth  400 non-null    object
 5   Resource_Allocation  400 non-null    float64
dtypes: float64(2), object(4)
memory usage: 18.9+ KB

In [ ]:
df_clean['Signal_Strength'] = df_clean['Signal_Strength'].str.replace('dBm','').astype('float')
df_clean.head()

,Application_Type,Signal_Strength,Latency,Required_Bandwidth,Allocated_Bandwidth,Resource_Allocation
0,Video_Call,-75.0,0.030,10 Mbps,15 Mbps,0.70
1,Voice_Call,-80.0,0.020,100 Kbps,120 Kbps,0.80
2,Streaming,-85.0,0.040,5 Mbps,6 Mbps,0.75
3,Emergency_Service,-70.0,0.010,1 Mbps,1.5 Mbps,0.90
4,Online_Gaming,-78.0,0.025,2 Mbps,3 Mbps,0.85

In [ ]:
def Kbps_to_Mbps(BW):
  BW = BW.split(' ')
  if BW[1] == 'Kbps':
    return float(BW[0]) / 1000
  else:
    return float(BW[0])

In [ ]:
df_clean['Required_Bandwidth(Mbps)'] = df_clean['Required_Bandwidth'].apply(Kbps_to_Mbps)
df_clean['Allocated_Bandwidth(Mbps)'] = df_clean['Allocated_Bandwidth'].apply(Kbps_to_Mbps)

In [ ]:
df_clean = df_clean.drop(['Required_Bandwidth','Allocated_Bandwidth'], axis='columns')
df_clean.head()

,Application_Type,Signal_Strength,Latency,Resource_Allocation,Required_Bandwidth(Mbps),Allocated_Bandwidth(Mbps)
0,Video_Call,-75.0,0.030,0.70,10.0,15.00
1,Voice_Call,-80.0,0.020,0.80,0.1,0.12
2,Streaming,-85.0,0.040,0.75,5.0,6.00
3,Emergency_Service,-70.0,0.010,0.90,1.0,1.50
4,Online_Gaming,-78.0,0.025,0.85,2.0,3.00

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Application_Type           400 non-null    object
 1   Signal_Strength            400 non-null    float64
 2   Latency                    400 non-null    float64
 3   Resource_Allocation        400 non-null    float64
 4   Required_Bandwidth(Mbps)   400 non-null    float64
 5   Allocated_Bandwidth(Mbps)  400 non-null    float64
dtypes: float64(5), object(1)
memory usage: 18.9+ KB

In [ ]:
dummies = pd.get_dummies(df_clean.Application_Type, drop_first=True , dtype=int)
dummies.head()

,Emergency_Service,File_Download,IoT_Temperature,Online_Gaming,Streaming,Video_Call,Video_Streaming,VoIP_Call,Voice_Call,Web_Browsing
0,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0

In [ ]:
df_clean = pd.concat([df_clean,dummies], axis='columns')
df_clean = df_clean.drop('Application_Type', axis='columns')
df_clean.head()

,Signal_Strength,Latency,Resource_Allocation,Required_Bandwidth(Mbps),Allocated_Bandwidth(Mbps),Emergency_Service,File_Download,IoT_Temperature,Online_Gaming,Streaming,Video_Call,Video_Streaming,VoIP_Call,Voice_Call,Web_Browsing
0,-75.0,0.030,0.70,10.0,15.00,0,0,0,0,0,1,0,0,0,0
1,-80.0,0.020,0.80,0.1,0.12,0,0,0,0,0,0,0,0,1,0
2,-85.0,0.040,0.75,5.0,6.00,0,0,0,0,1,0,0,0,0,0
3,-70.0,0.010,0.90,1.0,1.50,1,0,0,0,0,0,0,0,0,0
4,-78.0,0.025,0.85,2.0,3.00,0,0,0,1,0,0,0,0,0,0